name: fanofa
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  core:
    path: core
  data:
    path: data
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  country_picker: ^2.0.26
  #json_annotation: ^4.9.0
  #injectable: ^2.4.2
  #get_it: ^7.7.0

  #path_provider: ^2.1.3
  permission_handler: ^11.3.1
  #retry: ^3.1.2
  flutter_local_notifications: ^17.2.1+2
  #shared_preferences: ^2.2.3

  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3
  firebase_messaging: ^15.0.3
  firebase_core: ^3.2.0


  #dio: ^5.5.0+1
  #uuid: ^4.4.2
  #hive: ^2.2.3
  #crypto: ^3.0.3
  #encrypt: ^5.0.3
  #socket_io_client: ^2.0.3+1
  gap: ^3.0.1
  image_picker: ^1.1.2
  extended_image: ^8.2.1
  #device_info_plus: ^10.1.0
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  lottie: ^3.1.2
  version: ^3.0.2
  animate_do: ^3.3.4
  qr_flutter: ^4.1.0
  animations: ^2.0.11
  mime: ^1.0.5
  #http_parser: 4.0.2
  cupertino_icons: ^1.0.8
  event_bus: ^2.0.1
  cached_network_image: ^3.4.1
  app_links: ^6.3.2
  recaptcha_enterprise_flutter: ^18.6.1
  flutter_gcaptcha_v3: ^2.1.1
  flutter_recaptcha_v2_compat: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.6.1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200

flutter_intl:
  enabled: true
  class_name: Fanofaocalizations
  arb_dir: lib/src/app/localization/arb/
  output_dir: lib/src/app/localization/generated/
  use_deferred_loading: true
