name: network
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  crypto: ^3.0.5
  dio: ^5.7.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  hive: ^2.2.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^2.0.1
